version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: finwise-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Akashd@123
      MYSQL_DATABASE: FinWise
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: finwise-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/FinWise
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Akashd@123
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: finwise-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
